site_name: FastAPI Rate Limiter

theme:
  icon:
    logo: material/car-cruise-control
  name: material
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: teal
    toggle:
      icon: material/brightness-6
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: teal
    accent: teal
    toggle:
      icon: material/brightness-6
      name: "Switch to light mode"
